-- =====================================================================
-- Seoul Drop · Seed de catálogo (30 productos demo)
-- Generado automáticamente desde lib/data.ts — NO editar a mano.
-- Ejecutar DESPUÉS de 01-catalog.sql en el SQL Editor de Supabase.
-- =====================================================================

insert into public.catalog_products
  (id, slug, name, brand, category, price, original_price, description, full_description,
   badges, badge_color, rating, reviews, stock, tags, gradient, featured, is_new, sort_order)
values
  ($txt$1$txt$, $txt$cosrx-snail-mucin-96-essence$txt$, $txt$Advanced Snail 96 Mucin Power Essence$txt$, $txt$COSRX$txt$, $txt$kbeauty$txt$, 89000, 108000, $txt$La esencia viral de baba de caracol que repara y llena de luz. 96% de secreción filtrada.$txt$, $txt$Uno de los productos más vendidos en Olive Young por más de 5 años consecutivos. La secreción filtrada de caracol al 96% hidrata intensamente, repara la barrera cutánea dañada y suaviza la textura irregular. Ideal para piel sensible, piel con cicatrices de acné o cualquier persona que busque una piel visiblemente más sana.$txt$, '{"Best Seller"}', $txt$#FF6B9D$txt$, 4.9, 1243, 18, '{"hidratación","reparación","anti-envejecimiento","baba de caracol"}', $txt$linear-gradient(135deg, #FFE4F0 0%, #FFCCE4 100%)$txt$, true, false, 0),
  ($txt$2$txt$, $txt$beauty-of-joseon-glow-serum$txt$, $txt$Glow Deep Serum Propolis + Niacinamide$txt$, $txt$Beauty of Joseon$txt$, $txt$kbeauty$txt$, 95000, NULL, $txt$Sérum con propóleo y niacinamida para una piel brillante y sin manchas desde la semana 1.$txt$, $txt$Inspirado en los rituales de belleza de la dinastía Joseon. El extracto de propóleo al 63% combinado con niacinamida al 2% unifica el tono de la piel, reduce manchas y aporta un glow natural que dura todo el día. Textura ligera, absorción inmediata. Dermatológicamente probado.$txt$, '{"Nuevo"}', $txt$#4ECDC4$txt$, 4.8, 892, 12, '{"manchas","luminosidad","niacinamida","propóleo"}', $txt$linear-gradient(135deg, #FFF4E0 0%, #FFE5B4 100%)$txt$, true, true, 1),
  ($txt$3$txt$, $txt$anua-heartleaf-77-toner$txt$, $txt$Heartleaf 77% Soothing Toner$txt$, $txt$ANUA$txt$, $txt$kbeauty$txt$, 78000, 92000, $txt$Tónico calmante con 77% de extracto de Houttuynia Cordata para pieles reactivas y enrojecidas.$txt$, $txt$El tónico más recomendado en Naver Beauty para piel sensible. El 77% de extracto de Heartleaf (Houttuynia Cordata) calma el enrojecimiento, reduce la inflamación y fortalece la barrera cutánea. Sin fragancia, sin colorantes. Ideal post-rutina o como primer paso de hidratación.$txt$, '{"Agotándose"}', $txt$#F39C12$txt$, 4.7, 764, 5, '{"calmante","piel sensible","rojeces","sin fragancia"}', $txt$linear-gradient(135deg, #E4FFE4 0%, #C4F0C4 100%)$txt$, true, false, 2),
  ($txt$4$txt$, $txt$laneige-lip-sleeping-mask-berry$txt$, $txt$Lip Sleeping Mask Intense Care Berry$txt$, $txt$Laneige$txt$, $txt$kbeauty$txt$, 65000, NULL, $txt$La mascarilla labial de noche más viral del mundo. Labios suaves y restaurados en una sola noche.$txt$, $txt$El producto icónico de Laneige que conquistó TikTok y las redes coreanas. La tecnología SleepTox™ trabaja mientras duermes: exfolia células muertas, sella la humedad y regenera los labios con manteca de murumuru y fruta de baya. Por la mañana tus labios están visiblemente más suaves y con más volumen.$txt$, '{"Viral TikTok"}', $txt$#9B59B6$txt$, 4.9, 2156, 25, '{"labios","hidratación","noche","viral"}', $txt$linear-gradient(135deg, #FFE4EE 0%, #FFB8D4 100%)$txt$, true, false, 3),
  ($txt$5$txt$, $txt$some-by-mi-aha-bha-pha-toner$txt$, $txt$AHA·BHA·PHA 30 Days Miracle Toner$txt$, $txt$Some By Mi$txt$, $txt$kbeauty$txt$, 72000, NULL, $txt$El tónico de los 3 ácidos que transforma tu piel en 30 días. Poros, brillo y textura mejorados.$txt$, $txt$Formulado con 7 tipos de ácidos botánicos + AHA/BHA/PHA en concentración suave pero efectiva. Diseñado para una transformación progresiva: exfolia suavemente, desobstruye poros y uniformiza la textura. Recomendado para principiantes en ácidos gracias a su pH equilibrado. Más de 3 millones de unidades vendidas.$txt$, '{"Best Seller"}', $txt$#FF6B9D$txt$, 4.6, 3421, 22, '{"exfoliación","poros","ácidos","textura"}', $txt$linear-gradient(135deg, #E8F4FF 0%, #C4DEFF 100%)$txt$, false, false, 4),
  ($txt$6$txt$, $txt$isntree-hyaluronic-sun-gel$txt$, $txt$Hyaluronic Acid Watery Sun Gel SPF50+ PA++++$txt$, $txt$Isntree$txt$, $txt$kbeauty$txt$, 88000, NULL, $txt$Bloqueador solar gel con ácido hialurónico. Sin residuo blanco, toque seco, hidratación todo el día.$txt$, $txt$El protector solar que dejó de ser una corvée. Textura gel ultrafina que se absorbe en segundos, sin residuo blanco (apto para todos los tonos de piel), sin fragancia y enriquecido con ácido hialurónico para hidratación sostenida. Ideal como último paso de rutina AM. Resistente al agua y sudor.$txt$, '{"Nuevo"}', $txt$#4ECDC4$txt$, 4.8, 541, 14, '{"SPF","solar","ácido hialurónico","toque seco"}', $txt$linear-gradient(135deg, #E0F4FF 0%, #B8E4FF 100%)$txt$, false, true, 5),
  ($txt$7$txt$, $txt$numbuzin-no3-serum$txt$, $txt$No.3 Skin Softening Serum$txt$, $txt$Numbuzin$txt$, $txt$kbeauty$txt$, 92000, 112000, $txt$Sérum de miel fermentada y niacinamida. Piel suave como seda, brillo natural sin maquillaje.$txt$, $txt$La línea favorita de las influencers de belleza coreanas en 2024. El Sérum No.3 combina miel fermentada al 71% con niacinamida para una piel softer al tacto y con un glow "glass skin" desde la primera aplicación. Textura acuosa no pegajosa. Apto para pieles grasas y mixtas.$txt$, '{"Hot"}', $txt$#E74C3C$txt$, 4.7, 418, 9, '{"glass skin","miel","niacinamida","suavidad"}', $txt$linear-gradient(135deg, #FFF8E0 0%, #FFE8A0 100%)$txt$, true, false, 6),
  ($txt$8$txt$, $txt$round-lab-birch-sunscreen$txt$, $txt$Birch Juice Moisturizing Sunscreen SPF50+$txt$, $txt$Round Lab$txt$, $txt$kbeauty$txt$, 85000, NULL, $txt$Protector solar con savia de abedul. Ultra hidratante, sin residuo blanco y con efecto luminoso.$txt$, $txt$Hecho con savia de abedul de Ullengdo Island, este protector solar es la fusión perfecta entre cuidado e hidratación. PA++++ protege de UVA y UVB, la savia de abedul hidrata en profundidad y el acabado luminoso reemplaza cualquier primer. Formulación sin alcohol, sin parabenos.$txt$, '{}', NULL, 4.7, 326, 16, '{"SPF","abedul","hidratante","luminoso"}', $txt$linear-gradient(135deg, #F0F8E8 0%, #D4EEB8 100%)$txt$, false, false, 7),
  ($txt$9$txt$, $txt$klairs-supple-preparation-toner$txt$, $txt$Supple Preparation Unscented Toner$txt$, $txt$Dear, Klairs$txt$, $txt$kbeauty$txt$, 76000, NULL, $txt$El tónico preparador para pieles hipersensibles. Sin fragancia, sin alcohol. Hidratación en capas.$txt$, $txt$Diseñado para las pieles más sensibles del mundo. El tónico preparador de Klairs sin fragancia crea la base perfecta para los siguientes productos de la rutina. Con ácido hialurónico, centella asiatica y vitamina B5. Técnica "3-Step Patting" recomendada para una hidratación máxima.$txt$, '{}', NULL, 4.6, 512, 20, '{"piel sensible","sin fragancia","hidratación","centella"}', $txt$linear-gradient(135deg, #F8F0FF 0%, #ECD4FF 100%)$txt$, false, false, 8),
  ($txt$10$txt$, $txt$torriden-dive-in-serum$txt$, $txt$DIVE-IN Low Molecule Hyaluronic Acid Serum$txt$, $txt$Torriden$txt$, $txt$kbeauty$txt$, 82000, NULL, $txt$Sérum de ácido hialurónico de molécula pequeña que penetra 12 capas de piel. Hidratación real.$txt$, $txt$A diferencia del HA convencional, las moléculas pequeñas de Torriden penetran hasta las capas profundas de la dermis para una hidratación desde adentro. 5 tipos de ácido hialurónico en distintos pesos moleculares, textura en gel ultraligera y efecto plumping visible. Dermatológicamente probado en pieles acneicas.$txt$, '{"Nuevo"}', $txt$#4ECDC4$txt$, 4.8, 287, 11, '{"ácido hialurónico","hidratación profunda","plumping","acné"}', $txt$linear-gradient(135deg, #E0ECFF 0%, #B4D0FF 100%)$txt$, false, true, 9),
  ($txt$11$txt$, $txt$blackpink-born-pink-album$txt$, $txt$Born Pink — 2nd Album (Versión Digipack B)$txt$, $txt$BLACKPINK / YG$txt$, $txt$kpop$txt$, 88000, NULL, $txt$El segundo álbum de estudio de BLACKPINK. Incluye photobook, photocard aleatoria y póster.$txt$, $txt$El álbum debut más esperado de 2022. Born Pink incluye los hits "Pink Venom", "Shut Down" y "Tally". Esta versión Digipack B incluye: photobook de 104 páginas, 1 photocard aleatoria de 8 posibles, 1 póster foldado y 1 sticker sheet. Sellado original de YG Entertainment, importado directamente de Corea.$txt$, '{"Best Seller"}', $txt$#FF6B9D$txt$, 4.9, 876, 7, '{"BLACKPINK","álbum","photocard","YG"}', $txt$linear-gradient(135deg, #FFD4E8 0%, #FFB0D0 100%)$txt$, true, false, 10),
  ($txt$12$txt$, $txt$bts-proof-standard$txt$, $txt$Proof — Anthology Album Standard Edition$txt$, $txt$BTS / HYBE$txt$, $txt$kpop$txt$, 82000, NULL, $txt$Álbum antología de BTS con sus mejores hits y 3 canciones nuevas. Photocard aleatoria de 7.$txt$, $txt$La compilación definitiva de BTS que celebra sus 9 años de carrera. 48 canciones incluyendo "Run BTS", "Yet To Come" y temas inéditos. Incluye: CD 3-disc, photobook de 232 páginas, 1 photocard aleatoria de los 7 miembros, mini-essay y sticker set. Directo del HYBE official shop en Seúl.$txt$, '{"Best Seller"}', $txt$#FF6B9D$txt$, 4.9, 1102, 4, '{"BTS","álbum","antología","HYBE"}', $txt$linear-gradient(135deg, #DDE8FF 0%, #B8CCFF 100%)$txt$, true, false, 11),
  ($txt$13$txt$, $txt$newjeans-get-up-album$txt$, $txt$Get Up — The 2nd EP (Bunny Beach Bag Ver.)$txt$, $txt$NewJeans / ADOR$txt$, $txt$kpop$txt$, 79000, NULL, $txt$El EP de NewJeans con "Super Shy" y "ETA". Incluye la icónica bolsa de playa + photocard.$txt$, $txt$La versión más buscada del EP Get Up de NewJeans. El Bunny Beach Bag incluye la bolsa tote exclusiva, tarjeta QR para versión digital, 1 photocard aleatoria (Minji, Hanni, Danielle, Haerin o Hyein), mini photobook y pegatinas. Diseño aesthetic que se volvió viral en toda Asia.$txt$, '{"Agotándose"}', $txt$#F39C12$txt$, 4.8, 634, 3, '{"NewJeans","álbum","bunny","ADOR"}', $txt$linear-gradient(135deg, #E8FFEE 0%, #C0F0CC 100%)$txt$, true, false, 12),
  ($txt$14$txt$, $txt$aespa-drama-album$txt$, $txt$Drama — The 4th Mini Album (Drama Ver.)$txt$, $txt$aespa / SM$txt$, $txt$kpop$txt$, 76000, NULL, $txt$El mini álbum más exitoso de aespa con "Drama" y "Armageddon". Photocard aleatoria de 4.$txt$, $txt$El comeback que consolidó a aespa como uno de los grupos más importantes de cuarta generación. Drama incluye: CD, photobook de 80 páginas, 1 photocard aleatoria (Karina, Giselle, Winter o Ningning), tarjeta de puntuación y sticker lenticular. Comprado en el SM Artium de Seúl.$txt$, '{"Nuevo"}', $txt$#4ECDC4$txt$, 4.7, 412, 9, '{"aespa","álbum","SM","cuarta generación"}', $txt$linear-gradient(135deg, #F0E0FF 0%, #D8B4FF 100%)$txt$, false, true, 13),
  ($txt$15$txt$, $txt$stray-kids-rockstar-album$txt$, $txt$Rock-Star — The 10th Mini Album (Standard)$txt$, $txt$Stray Kids / JYP$txt$, $txt$kpop$txt$, 82000, NULL, $txt$El álbum que rompió récords de Stray Kids. Incluye "Miroh (Rock Ver.)" y photocard aleatoria de 8.$txt$, $txt$Rock-Star debutó en #1 en Billboard 200, haciendo de Stray Kids el primer grupo de cuarta generación en lograrlo. Incluye: 2 CDs, photobook 112 páginas, 1 photocard aleatoria de los 8 miembros, una tarjeta de póster y sticker sheet. Versión Standard comprada en la tienda oficial JYP en Myeongdong.$txt$, '{"Best Seller"}', $txt$#FF6B9D$txt$, 4.8, 589, 6, '{"Stray Kids","álbum","JYP","rock"}', $txt$linear-gradient(135deg, #F8E8D0 0%, #F0C890 100%)$txt$, false, false, 14),
  ($txt$16$txt$, $txt$twice-ready-to-be-album$txt$, $txt$READY TO BE — 12th Mini Album (B Ver.)$txt$, $txt$TWICE / JYP$txt$, $txt$kpop$txt$, 78000, NULL, $txt$El mini álbum de TWICE con "SET ME FREE" y "MOONLIGHT SUNRISE". Photocard aleatoria de 9.$txt$, $txt$TWICE celebra su décimo año de carrera con un álbum lleno de poder y madurez. Ready to Be incluye: CD, photobook de 88 páginas, 1 photocard aleatoria de las 9 integrantes, carta de póster y pegatinas holográficas. Importado directamente del JYP Shop online con certificado de autenticidad.$txt$, '{}', NULL, 4.7, 347, 11, '{"TWICE","álbum","JYP","girl group"}', $txt$linear-gradient(135deg, #FFE0F8 0%, #FFC0F0 100%)$txt$, false, false, 15),
  ($txt$17$txt$, $txt$artbox-cherry-blossom-washi-set$txt$, $txt$Cherry Blossom Washi Tape Set x10$txt$, $txt$Artbox$txt$, $txt$stationery$txt$, 32000, NULL, $txt$Set de 10 washi tapes de flor de cerezo. La papelería más kawaii de la tienda flagship de Artbox en Hongdae.$txt$, $txt$Artbox es la meca de la papelería kawaii en Corea del Sur. Este set de colección de temporada incluye 10 rollos de washi tape con motivos de flor de cerezo en diferentes anchos (10mm y 15mm). Adhesivo removible, papel de arroz japonés. Edición limitada comprada en la tienda de Hongdae.$txt$, '{"Edición Limitada"}', $txt$#FF6B9D$txt$, 4.8, 234, 15, '{"washi tape","kawaii","Artbox","flor de cerezo"}', $txt$linear-gradient(135deg, #FFE4EE 0%, #FFCCE0 100%)$txt$, false, false, 16),
  ($txt$18$txt$, $txt$kakao-friends-ryan-notebook-set$txt$, $txt$Ryan & Choonsik Notebook Set x2 (A5)$txt$, $txt$Kakao Friends$txt$, $txt$stationery$txt$, 38000, NULL, $txt$Set de 2 libretas A5 de Ryan y Choonsik. Papel de 100gsm, diseño oficial de Kakao Friends.$txt$, $txt$Los personajes más queridos de Korea en formato libreta. Set incluye 1 libreta cuadriculada Ryan (120 páginas) y 1 libreta rayada Choonsik (120 páginas). Formato A5, papel 100gsm, tapa dura ilustrada. Diseño oficial comprado en la tienda flagship Kakao Friends en Gangnam, Seúl.$txt$, '{"Nuevo"}', $txt$#4ECDC4$txt$, 4.7, 189, 12, '{"Ryan","Kakao Friends","libreta","A5"}', $txt$linear-gradient(135deg, #FFF4CC 0%, #FFE880 100%)$txt$, false, true, 17),
  ($txt$19$txt$, $txt$bt21-sticky-notes-pack$txt$, $txt$BT21 Mega Sticky Notes Pack (7 bloques)$txt$, $txt$Line Friends / BTS$txt$, $txt$stationery$txt$, 25000, NULL, $txt$Pack de 7 bloques de sticky notes con los 7 personajes BT21. Papel autoadhesivo de calidad.$txt$, $txt$Los iconos de BT21 (Koya, RJ, Shooky, Mang, Chimmy, Tata y Van) en 7 bloques de 50 hojas cada uno. Diferentes formas y tamaños, papel autoadhesivo de calidad premium. Comprado en la tienda oficial Line Friends del COEX Mall en Seúl. Ideal para fans o como regalo.$txt$, '{}', NULL, 4.6, 312, 28, '{"BT21","BTS","sticky notes","Line Friends"}', $txt$linear-gradient(135deg, #E0F0FF 0%, #B8D8FF 100%)$txt$, false, false, 18),
  ($txt$20$txt$, $txt$artbox-gel-pen-set-20$txt$, $txt$Pastel Gel Pen Set x20 Colores$txt$, $txt$Artbox$txt$, $txt$stationery$txt$, 28000, NULL, $txt$20 bolígrafos de gel en colores pastel. Tinta suave, punta fina 0.5mm. El favorito del bullet journal coreano.$txt$, $txt$El set completo para bullet journaling y estudio al estilo coreano. 20 colores pasteles únicos que no se consiguen fácilmente fuera de Corea. Tinta a base de gel de secado rápido, punta de 0.5mm para escritura precisa. No mancha, no corre. Comprado en la tienda flagship Artbox de Myeongdong.$txt$, '{"Best Seller"}', $txt$#FF6B9D$txt$, 4.8, 421, 18, '{"bolígrafos","gel","pastel","bullet journal"}', $txt$linear-gradient(135deg, #F0F8E0 0%, #D4EEB4 100%)$txt$, false, false, 19),
  ($txt$21$txt$, $txt$artbox-mini-masking-tape-5pack$txt$, $txt$Mini Masking Tape Collection x5 (Flores y Fruta)$txt$, $txt$Artbox$txt$, $txt$stationery$txt$, 22000, NULL, $txt$5 rollos de masking tape mini con patrones de flores y frutas. 7mm de ancho, adhesivo suave.$txt$, $txt$Colección de temporada verano 2024 de Artbox. 5 rollos de masking tape en formato mini (7mm) con diseños ilustrados de flores y frutas tropicales. Papel de arroz japonés, adhesivo repositionable que no deja residuo. Perfecto para decorar agendas, cuadernos y packagings de regalo.$txt$, '{}', NULL, 4.5, 156, 24, '{"masking tape","flores","kawaii","Artbox"}', $txt$linear-gradient(135deg, #FFEEE0 0%, #FFD8B8 100%)$txt$, false, false, 20),
  ($txt$22$txt$, $txt$buldak-ramen-original-5pack$txt$, $txt$Buldak Bokkeummyeon Ramen Pack x5 (Original)$txt$, $txt$Samyang$txt$, $txt$snacks$txt$, 38000, NULL, $txt$El ramen más picante y viral del mundo. El clásico original que inició el Buldak challenge.$txt$, $txt$El ramen que conquistó TikTok, YouTube y el mundo entero. Buldak Bokkeummyeon (pollo en llamas) es el ramen seco más vendido en Corea. Salsa intensa, noodles chewy, nivel de picante extremo (4,404 unidades Scoville). Pack de 5 unidades compradas en el GS25 de Myeongdong.$txt$, '{"Viral"}', $txt$#E74C3C$txt$, 4.9, 1876, 35, '{"ramen","picante","viral","Samyang"}', $txt$linear-gradient(135deg, #FFE0CC 0%, #FFB090 100%)$txt$, true, false, 21),
  ($txt$23$txt$, $txt$buldak-ramen-queso-5pack$txt$, $txt$Buldak Bokkeummyeon Ramen x5 (Carbonara Queso)$txt$, $txt$Samyang$txt$, $txt$snacks$txt$, 42000, NULL, $txt$La versión cremosa y menos picante del Buldak. Sabor a carbonara con queso. Perfecta para iniciar.$txt$, $txt$Para los que quieren el Buldak pero con un toque más suave. La versión Carbonara combina la salsa de pollo buldak con una crema de queso que equilibra el picante. Se volvió viral como "el ramen para principiantes del picante". Pack de 5 unidades. Nivel de picante: 2,600 Scoville.$txt$, '{"Hot"}', $txt$#E74C3C$txt$, 4.8, 1234, 28, '{"ramen","carbonara","queso","Samyang"}', $txt$linear-gradient(135deg, #FFF8CC 0%, #FFE880 100%)$txt$, false, false, 22),
  ($txt$24$txt$, $txt$pepero-chocolate-5pack$txt$, $txt$Pepero Chocolate Original x5 Cajas$txt$, $txt$Lotte$txt$, $txt$snacks$txt$, 22000, NULL, $txt$Los palitos de galleta bañados en chocolate que celebran el "Día del Pepero" en Corea cada 11/11.$txt$, $txt$Pepero es uno de los snacks más icónicos de Corea del Sur. Los palitos crujientes de galleta cubiertos de chocolate belga han sido el regalo favorito en Corea desde 1983. Pack de 5 cajas individuales de 54g. Compradas en el CU Convenience Store de Insadong. Perfectas para regalar.$txt$, '{}', NULL, 4.7, 842, 42, '{"pepero","chocolate","galleta","Lotte"}', $txt$linear-gradient(135deg, #F0E0D0 0%, #D4B090 100%)$txt$, false, false, 23),
  ($txt$25$txt$, $txt$orion-choco-pie-12pack$txt$, $txt$Choco Pie Original x12 Unidades$txt$, $txt$Orion$txt$, $txt$snacks$txt$, 28000, NULL, $txt$El postre coreano clásico: bizcocho suave, crema de malvavisco y cobertura de chocolate.$txt$, $txt$El Choco Pie de Orion es tan icónico que tiene su propio museo en Corea. Tres capas de bondad: bizcocho de vainilla súper esponjoso, marshmallow de vainilla y cobertura de chocolate. 12 unidades individuales empacadas. No confundir con imitaciones: este es el original coreano, comprado en Seúl.$txt$, '{"Clásico"}', $txt$#9B59B6$txt$, 4.8, 1567, 38, '{"choco pie","chocolate","malvavisco","Orion"}', $txt$linear-gradient(135deg, #E8D0C0 0%, #C4A080 100%)$txt$, false, false, 24),
  ($txt$26$txt$, $txt$nongshim-shin-ramyun-5pack$txt$, $txt$Shin Ramyun Original x5 Packs$txt$, $txt$Nongshim$txt$, $txt$snacks$txt$, 35000, NULL, $txt$El ramen coreano más famoso del mundo. Picante, sabroso y con caldoo profundo. El referente del ramen.$txt$, $txt$Shin Ramyun es el ramen más exportado de Corea y referente mundial del género. Caldo de res y vegetales con un nivel de picante notable pero manejable. Noodles al dente, paquete de verduras deshidratadas incluido. Se prepara en 4 minutos. 5 packs comprados en el Lotte Mart de Itaewon.$txt$, '{"Clásico"}', $txt$#9B59B6$txt$, 4.8, 2134, 45, '{"ramen","shin ramyun","Nongshim","picante"}', $txt$linear-gradient(135deg, #FFD8C0 0%, #FFB080 100%)$txt$, true, false, 25),
  ($txt$27$txt$, $txt$haitai-honey-butter-chips-3pack$txt$, $txt$Honey Butter Chip x3 Bolsas (60g c/u)$txt$, $txt$Haitai / Crown$txt$, $txt$snacks$txt$, 34000, NULL, $txt$Las papas fritas que causaron escasez en Corea. Miel, mantequilla y sal. Irresistibles.$txt$, $txt$En 2014, los Honey Butter Chips causaron una crisis de escasez en Corea: vendían 10 veces más de lo que se podía producir. El combo de miel, mantequilla de calidad y sal de mar crea un sabor adictivo que no existe en ningún otro chip del mundo. 3 bolsas de 60g, textura crunchy perfecta.$txt$, '{"Viral"}', $txt$#E74C3C$txt$, 4.9, 987, 20, '{"papas","miel","mantequilla","Haitai"}', $txt$linear-gradient(135deg, #FFF4CC 0%, #FFE480 100%)$txt$, false, false, 26),
  ($txt$28$txt$, $txt$lotte-kancho-biscuit-6pack$txt$, $txt$Kancho Biscuit — Chocolate Fill x6 Cajas$txt$, $txt$Lotte$txt$, $txt$snacks$txt$, 24000, NULL, $txt$Galletitas de cancha redondas rellenas de chocolate. El snack favorito de los niños coreanos por 40 años.$txt$, $txt$Kancho son las galletas redondas que toda persona que ha visitado Corea ha comido. Masa crujiente de mantequilla con relleno cremoso de cacao. 6 cajas de 42g, perfectas para picar. Compradas en el Lotte World Mall de Jamsil. El snack que más piden los colombianos que han estado en Corea.$txt$, '{}', NULL, 4.6, 534, 50, '{"galletas","chocolate","Lotte","snack"}', $txt$linear-gradient(135deg, #F4E4D0 0%, #D8B890 100%)$txt$, false, false, 27),
  ($txt$29$txt$, $txt$samsung-galaxy-buds2-pro$txt$, $txt$Galaxy Buds2 Pro — Cancelación de Ruido ANC$txt$, $txt$Samsung$txt$, $txt$tech$txt$, 380000, NULL, $txt$Los audífonos inalámbricos premium de Samsung con ANC de clase mundial. Comprados en el Samsung DX de Gangnam.$txt$, $txt$Los Galaxy Buds2 Pro son los mejores audífonos in-ear de Samsung: cancelación activa de ruido clase 1 (reducción hasta 98%), audio Hi-Fi de 24bit, Buds360 XT™ para audio inmersivo y batería de 8h con estuche (hasta 29h total). Resistentes al agua IPX7. Comprados en la tienda Samsung DX Experience de Gangnam, Seúl, con garantía original.$txt$, '{"Premium"}', $txt$#1A1A1A$txt$, 4.8, 234, 4, '{"Samsung","audífonos","ANC","inalámbrico"}', $txt$linear-gradient(135deg, #D8E4F8 0%, #A8C4F0 100%)$txt$, true, false, 28),
  ($txt$30$txt$, $txt$baseus-usbc-hub-7in1$txt$, $txt$Baseus USB-C Hub 7-en-1 (4K HDMI + PD 100W)$txt$, $txt$Baseus$txt$, $txt$tech$txt$, 145000, NULL, $txt$Hub USB-C con HDMI 4K, 3×USB-A, lector SD/TF y carga rápida 100W. Plug & play, sin drivers.$txt$, $txt$El hub esencial para MacBook, Galaxy o cualquier portátil con USB-C. 7 puertos: 1×HDMI 4K@60Hz, 3×USB-A 3.0, 1×USB-C PD 100W, 1×SD y 1×TF. Aluminio premium, transmisión de datos a 5Gbps. Sin necesidad de drivers, compatible con Mac, Windows y Android. Comprado en el Yongsan Electronics Market de Seúl.$txt$, '{"Nuevo"}', $txt$#4ECDC4$txt$, 4.7, 156, 8, '{"USB-C","hub","HDMI","MacBook"}', $txt$linear-gradient(135deg, #D4F0E8 0%, #A4DCc8 100%)$txt$, false, true, 29)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  price = excluded.price,
  original_price = excluded.original_price,
  description = excluded.description,
  full_description = excluded.full_description,
  badges = excluded.badges,
  badge_color = excluded.badge_color,
  rating = excluded.rating,
  reviews = excluded.reviews,
  stock = excluded.stock,
  tags = excluded.tags,
  gradient = excluded.gradient,
  featured = excluded.featured,
  is_new = excluded.is_new,
  sort_order = excluded.sort_order;
